spring:
  application:
    name: dynamic-datasource-spring-boot-starter
  datasource:
    hikari:
      jdbc-url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.mysql.com:3306/database?useUnicode=true&characterEncoding=utf-8&useSSL=false}
      username: ${SPRING_DATASOURCE_USERNAME:hdsp_dev}
      password: ${SPRING_DATASOURCE_PASSWORD:hdsp_dev}
      # 连接池最小空闲连接数
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:20}
      # 连接池允许的最大连接数
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:200}
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}
jm:
  dynamic:
    datasource:
      pg:
        jdbc-url: ${DYNAMIC_GP_URL:jdbc:postgresql://db.postgresql.com:5432/databaseName?searchpath=schema}
        username: ${DYNAMIC_GP_USERNAME:cabbeen}
        password: ${DYNAMIC_GP_PASSWORD:cabbeen}
        driver-class-name: ${DYNAMIC_GP_DRIVER:org.postgresql.Driver}

